name: CI

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

jobs:
  Ubuntu:
    name: 'Ubuntu (${{ matrix.python }}${{ matrix.extra_name }})'
    timeout-minutes: 10
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        python: ['pypy-3.6', 'pypy-3.7', '3.6', '3.7', '3.8', '3.9', '3.6-dev', '3.7-dev', '3.8-dev', '3.9-dev', '3.10-dev']
        check_formatting: ['0']
        pypy_nightly_branch: ['']
        extra_name: ['']
        include:
          - python: '3.8'
            check_formatting: '1'
            extra_name: ', check formatting'
          - python: '3.8'
            check_typing: '1'
            extra_name: ', check typing'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        if: "!endsWith(matrix.python, '-dev')"
        with:
          python-version: '${{ matrix.python }}'
      - name: Setup python (dev)
        uses: deadsnakes/action@v2.0.2
        if: endsWith(matrix.python, '-dev')
        with:
          python-version: '${{ matrix.python }}'
      - name: Maybe set RUNTIME_ONLY
        if: ${{ startsWith(matrix.python, 'pypy') }}
        shell: bash
        run: echo "RUNTIME_ONLY=1" >> $GITHUB_ENV
      - name: Run tests
        run: ./ci.sh
        env:
          PYPY_NIGHTLY_BRANCH: '${{ matrix.pypy_nightly_branch }}'
          CHECK_FORMATTING: '${{ matrix.check_formatting }}'
          CHECK_TYPING: '${{ matrix.check_typing }}'
          # Should match 'name:' up above
          JOB_NAME: 'Ubuntu (${{ matrix.python }}${{ matrix.extra_name }})'
